name: Publish Voxel51 Docs

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/web-app-build.yaml
      - placeholder/** # change this when actually built to be the source directory

env:
  BUILT_DOCS_DIR: placeholder/ # Switch this out later

jobs:
  publish-docs: # You might want a build-docs section above this or a separate reusable workflow
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_DOCS_PROJECT }}
          service_account: ${{ secrets.GCP_DOCS_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDP_SECRET_NAME }}
      
      - name: Set Up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Sync to bucket
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: ${{ env.BUILT_DOCS_DIR }}
          destination: ${{ secrets.GCP_DOCS_LOCATION }}
          parent: false
